language: node_js
sudo: true
cache:
  directories:
    - node
    - node_modules

dist: trusty

node_js:
  - '6.1.0'

branches:
  only:
  - master
  - develop

before_install:
 - cp src/environments/environment.ci.ts src/environments/environment.dev.ts
 - cp src/environments/environment.ci.ts src/environments/environment.ts
 - npm install -g angular-cli
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script:
 - ng test --watch false # http://mseemann.de/frontend/2016/05/31/setup-angular-2-app-part-1.html
 # - ng serve &
 # - ng e2e

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

  slack:
    secure: Wj/fGdqfmaJGynB099qilqn9mq+2R3eh1xdUvrJr7CSk+NxEOQ8ByA4cRnNoo1xbFkqH+gfx5Y+u7VQcDGCsNShdo2w5dwzu7sgCk8De7jcP1BBVewx0ECAj8uVJpiPuSACT7wH85VCKP5FBBbcqjCFcbrTnGLMY7O22BcNPNIPnbJvzinT/w+huffe//+W+RRZ0mnjTO/xOc7UfNcqf9cqqb0hA73+wmpK1rkxN7eOk8D/NPZ1Wd8f7p6yjR6t6jqcNBv0nmITyMFyfAP9Yqe4t7qf2zLYIn1Iz6wUaHOiltrccjmwGG+ulkKjXgM+FxjyYbSK6/FM60GiYNnoRRZRyrGq2jrgl0DdCxCVEIzdzFmYVjkjc9GEaakz/t31qplzVPnPvvNN7t2W7j4LjcOBJ+zlcyVqtEn7iGo0PoZXuQSeNb7HCHu0oPJ6NIwaHE5QkiVIN+ST80uiCnwkKRIJ+PMpggydYsbDp70/UZymOsk6Pw9OYOQMx1Dcy5RIRvw+gv6ZJICKD5lfeHv0Seuqp+yanFPyOUAnfuVgZ1SjkqsiKswBaBjCVYHoCMXzkTkObDJ8/cn5PNZYuS4azrs/TGZy94eBE6N1kA0jG8tLhh2iLrfipwR2PAF3T1yf8Q2CU5b/YDP1Cl454UieVvjM8KxHpHSse/Up5XWeXjTc=


